version: '3'

services:
  langkah-app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: langkah-app
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env